#
# This source file is part of the FA2021 open source project
#
# SPDX-FileCopyrightText: 2019-2021 Paul Schmiedmayer and the project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

version: '3.3'

services:
  # An Apodini Buoy Web Service
  buoy-web-service:
    container_name: "buoy-web-service"
    image: "ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:latest"
    # Expose port 8080 of container on port 443 of host
    ports:
      - "80:80"
    # Mount directory for config and sensor data
    privileged: true
    user: root
    volumes:
      - ../buoy:/buoy
      - ${ENV_DEPLOYPATH}:/app/tmp:Z
    command: ${ENV_COMMAND}
