#
# This source file is part of the FA 2021 open source project
#
# SPDX-FileCopyrightText: 2021 Paul Schmiedmayer and the FA 2021 project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#

name: Build Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  dockerARM64:
    name: Docker Build and Push ARM64 Images
    runs-on: ARM64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push web service docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            baseimage=swiftarm/swift:5.5.1-ubuntu-focal
          push: true
          tags: ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:latest-arm64,ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:${{ steps.latesttag.outputs.tag }}-arm64
      - name: Build and push Buoy Post Discovery Action docker image
        uses: docker/build-push-action@v2
        with:
          context: BuoyPostDiscoveryAction
          file: Dockerfile
          push: true
          tags: ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:latest-arm64,ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:${{ steps.latesttag.outputs.tag }}-arm64
  dockerAMD64:
    name: Docker Build and Push AMD64 Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push web service docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            baseimage=swift:focal
          push: true
          tags: ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:latest-amd64,ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:${{ steps.latesttag.outputs.tag }}-amd64
      - name: Build and push Buoy Post Discovery Action docker image
        uses: docker/build-push-action@v2
        with:
          context: BuoyPostDiscoveryAction
          file: Dockerfile
          push: true
          tags: ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:latest-amd64,ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:${{ steps.latesttag.outputs.tag }}-amd64
  dockermanifest:
    needs: [dockerARM64, dockerAMD64]
    name: Create Multi-CPU Architecture Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get latest tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: latest
      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and Push web service Multi Architecture Image
        run: |
            docker manifest create ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:latest \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:latest-amd64 \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:latest-arm64
            docker manifest create ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:${{ steps.latesttag.outputs.tag }} \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:${{ steps.latesttag.outputs.tag }}-amd64 \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:${{ steps.latesttag.outputs.tag }}-arm64
            docker manifest push ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:latest
            docker manifest push ghcr.io/fa21-collaborative-drone-interactions/buoy-webservice:${{ steps.latesttag.outputs.tag }}
      - name: Create and Push Buoy Post Discovery Action Multi Architecture Image
        run: |
            docker manifest create ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:latest \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:latest-amd64 \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:latest-arm64
            docker manifest create ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:${{ steps.latesttag.outputs.tag }} \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:${{ steps.latesttag.outputs.tag }}-amd64 \
              --amend ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:${{ steps.latesttag.outputs.tag }}-arm64
            docker manifest push ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:latest
            docker manifest push ghcr.io/fa21-collaborative-drone-interactions/buoy-post-discovery-action:${{ steps.latesttag.outputs.tag }}
